project:
  type: website

website:
  title: "2026 Brazil Workshop on the Use of Alternative Data Sources for Consumer Price Statistics"
  repo-url: https://github.com/UN-Task-Team-for-Scanner-Data/brazil-workshop-on-use-of-ads/
  issue-url: https://github.com/UN-Task-Team-for-Scanner-Data/brazil-workshop-on-use-of-ads//issues/new
  repo-actions: [source, issue]
  # favicon: docs/images/logo.png
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  navbar:
    background: primary
    search: true
    title: "2026 Brazil Workshop on the Use of Alternative Data Sources for Consumer Price Statistics"

    right:
      - icon: globe
        text: "UN Task e-handbook"
        href: https://unstats.un.org/wiki/display/GWGSD/Handbook+on+utilising+new+data+sources+in+the+production+of+consumer+price+statistics
      - icon: person-raised-hand
        text: "About the UN Task Team"
        href: https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml

    left:
      - href: content/index.qmd
        text: Home
      - text: "Agenda"
        href: content/agenda.qmd

format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: cyborg