project:
  type: website

website:
  title: "Brazil Workshop on the use of Alternative Data Sources for Consumer Price Statistics"
  repo-url: https://github.com/UN-Task-Team-for-Scanner-Data/brazil-workshop-on-use-of-ads/
  issue-url: https://github.com/UN-Task-Team-for-Scanner-Data/brazil-workshop-on-use-of-ads//issues/new
  repo-actions: [source, issue]
  # favicon: docs/images/logo.png
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  navbar:
    background: primary
    search: true
    title: "Workshop: Alternative Data for Consumer Price Statistics"

    right:
      - icon: box-arrow-up-right
        menu:
          - text: "About the UN Task Team for Scanner Data"
            href: https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml
          - text: "Read the UN Task e-handbook"
            href: https://unstats.un.org/wiki/display/GWGSD/Handbook+on+utilising+new+data+sources+in+the+production+of+consumer+price+statistics
          - text: "2020 CPI Manual and related resources"
            href: https://www.imf.org/en/data/statistics/cpi-manual

    left:
      - icon: house
        href: content/index.qmd
        text: Home
      - icon: calendar2-week
        text: "Agenda"
        href: content/agenda.qmd
      - icon: code
        text: Examples
        menu:
          - href: content/multilateral_examples.qmd
          - href: content/processing_examples.qmd

format:
  html:
    toc: true
    theme: 
      light: zephyr
      dark: cyborg