---
title: "Event agenda"
format:
  html:
    toc: true
    toc-expand: 2
---

# Workshop Format and Structure

The workshop is proposed as a **five-day virtual event**, combining synchronous and asynchronous activities, to balance live interaction with flexibility for participants.

-   **Synchronous sessions** are proposed for **Monday, Wednesday, and Friday**, from **10:00 to 12:00 (Brasília time, GMT-3)**. These sessions would focus on conceptual discussions, methodological guidance, live demonstrations, and interactive exchanges with the Task Team.

-   **Asynchronous activities** are proposed for **Tuesday and Thursday**, allowing participants to engage with selected materials, exercises, or practical tasks at their own pace. These activities would build on the content of the synchronous sessions and reinforce key concepts and tools

# Day by day agenda

## Monday June 22

| Time | **Session** | **Speakers / Facilitator** |
|-----------|---------------------------------------|---------------------|
| 10:00 – 10:15 | Introduction to the workshop and tour de table | Tanya Flower (UNTT, UK ONS), Vladimir Goncalves Miranda /Lincoln |
| 10:15 – 10:50 | Overview of alternative data sources for CPI compilation (Scanner data, web scraping, APIs, administrative data) | Federico Polidoro (UNTT, World Bank) |
| 10:50 – 11:15 | Overview of the main challenges to obtain alternative data for CPI compilation | Federico Polidoro (UNTT, World Bank) |
| 11:15 – 12:00 | Alternative data preparation, cleaning, and classification for price statistics. Illustration for Tuesday asynchronous activities | Sandra Andric (UNTT, Statistics Canada), Serge Goussev (UNTT, Statistics Canada) |

## Tuesday June 23

Asynchronous Activities (self paced)

## Wednesday June 24

| Time | **Session** | **Speakers / Facilitator** |
|----------------|-------------------------------------|-------------------|
| 10:00 – 10:30 | Report on the asynchronous activities | Participants, All the speakers of Day 1 |
| 10:30 – 11:20 | Use of alternative data sources in CPI compilation. Bilateral and multilateral
indices | Helen Sands (UK ONS) |
| 11:20 – 12:00 | Introduction to tools and packages for multilateral indices using
scanner data and materials for Thursday asynchronous activities | Luigi Palumbo (UNTT, Bank of Italy), Oskar Eugster (UNTT, Statistics Switzerland) |

## Thrusday June 24

Asynchronous Activities (self paced)

## Friday June 26

| Time | **Session** | **Speakers / Facilitator** |
|----------------|-------------------------------------|-------------------|
| 10:00 – 10:45 | Report on the asynchronous activities and further discussion on
multilateral indices | Participants / All the speakers of Day 2 |
| 10:45 – 11:15 | Quality assurance, validation, and comparison with traditional price
data | Tanya Flower (UNTT, UK ONS) |
| 11:15 – 11:45 | Institutional and operational considerations for integrating scanner
data into regular statistical production | Helen Sands (UNTT, UK ONS) |
| 11:45 – 12:00 | Conclusion and way forward | Tanya Flower (UNTT, UK ONS), Vladimir Goncalves Miranda / Lincoln
Teixeira da Silva / Bruno Garcia / Paulo Tostes dos Santos (UN
Regional Hub, IBGE) |